text changes
descope-sample-apps/b2b-sample-app pull request #35
Opened 2023-01-25 13:19 UTC by amolthiteapptware

In the welcome banner. at the bottom - add "Currently using Descope Flows from Project ID <Project ID>". If project ID is the default one from Descope (part of the env variable)-  add "(Descope Default)" : Done

Change "sample consumer app" to "sample B2B app": Done/jki

2023-01-26 01:54 UTC, gshriki requested changes
We should also fix the other explanation - there is no checkin the B2B.
For now we can remove it, and only keep "try signing up"

2023-01-28 03:46 UTC, rishibhargava commented on src/components/welcomeModal/WelcomeModal.tsx
> +              Currently using Descope Flows from Project ID: {localStorage.getItem('projectId') ? localStorage.getItem('projectId') : '(Descope Default)'}
Change to 'Descope default project' - no () needed also.

2023-01-28 03:46 UTC, rishibhargava approved these changes

2023-01-30 04:30 UTC, amolthiteapptware commented on src/components/welcomeModal/WelcomeModal.tsx
> +              Currently using Descope Flows from Project ID: {localStorage.getItem('projectId') ? localStorage.getItem('projectId') : '(Descope Default)'}
Done

2023-01-31 05:57 UTC, merged